// Generated by gencpp from file moro_navigation_msgs/PlanPath.msg
// DO NOT EDIT!


#ifndef MORO_NAVIGATION_MSGS_MESSAGE_PLANPATH_H
#define MORO_NAVIGATION_MSGS_MESSAGE_PLANPATH_H

#include <ros/service_traits.h>


#include <moro_navigation_msgs/PlanPathRequest.h>
#include <moro_navigation_msgs/PlanPathResponse.h>


namespace moro_navigation_msgs
{

struct PlanPath
{

typedef PlanPathRequest Request;
typedef PlanPathResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PlanPath
} // namespace moro_navigation_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::moro_navigation_msgs::PlanPath > {
  static const char* value()
  {
    return "098f7f8b063d412adcf0fd12d1459840";
  }

  static const char* value(const ::moro_navigation_msgs::PlanPath&) { return value(); }
};

template<>
struct DataType< ::moro_navigation_msgs::PlanPath > {
  static const char* value()
  {
    return "moro_navigation_msgs/PlanPath";
  }

  static const char* value(const ::moro_navigation_msgs::PlanPath&) { return value(); }
};


// service_traits::MD5Sum< ::moro_navigation_msgs::PlanPathRequest> should match 
// service_traits::MD5Sum< ::moro_navigation_msgs::PlanPath > 
template<>
struct MD5Sum< ::moro_navigation_msgs::PlanPathRequest>
{
  static const char* value()
  {
    return MD5Sum< ::moro_navigation_msgs::PlanPath >::value();
  }
  static const char* value(const ::moro_navigation_msgs::PlanPathRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::moro_navigation_msgs::PlanPathRequest> should match 
// service_traits::DataType< ::moro_navigation_msgs::PlanPath > 
template<>
struct DataType< ::moro_navigation_msgs::PlanPathRequest>
{
  static const char* value()
  {
    return DataType< ::moro_navigation_msgs::PlanPath >::value();
  }
  static const char* value(const ::moro_navigation_msgs::PlanPathRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::moro_navigation_msgs::PlanPathResponse> should match 
// service_traits::MD5Sum< ::moro_navigation_msgs::PlanPath > 
template<>
struct MD5Sum< ::moro_navigation_msgs::PlanPathResponse>
{
  static const char* value()
  {
    return MD5Sum< ::moro_navigation_msgs::PlanPath >::value();
  }
  static const char* value(const ::moro_navigation_msgs::PlanPathResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::moro_navigation_msgs::PlanPathResponse> should match 
// service_traits::DataType< ::moro_navigation_msgs::PlanPath > 
template<>
struct DataType< ::moro_navigation_msgs::PlanPathResponse>
{
  static const char* value()
  {
    return DataType< ::moro_navigation_msgs::PlanPath >::value();
  }
  static const char* value(const ::moro_navigation_msgs::PlanPathResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MORO_NAVIGATION_MSGS_MESSAGE_PLANPATH_H
